version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
      - mongo
      - redis
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - MONGO_URI=mongodb://mongo:27017/
    ports:
      - "5000:5000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    container_name: mongodb
    restart: on-failure
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  redis:
    image: redis
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"