# Generated by Django 5.1.4 on 2025-01-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('coauthors', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='main.category')),
            ],
        ),
    ]
